[package]
name = "parser"
version = "0.1.0"
edition = "2021"

[dependencies]
markdown = { git = "https://github.com/wooorm/markdown-rs.git" }
config = { path = "../config" }
serde = "1.0.217"
serde_json = "1.0.138"
mdast_util_to_markdown = { git = "https://github.com/wooorm/markdown-rs.git" }
